export default {
    'aboutDescriptionP1': {
        en: 'Musica para Respirar (Music to Breathe) 24/7 is a project of the Bolivian Chamber Music Society (La Sociedad) that brings together professional musicians from across Latin America to offer online concerts to people impacted by COVID-19 everywhere. The concerts are free and provided via video calls by teams of musicians for 24 hours-a-day over the course of a week.',
        es: 'Música para Respirar 24/7 es una instalación artística en la cual músicos y músicas de alrededor del mundo están disponibles las 24 horas del día durante una semana, listos para tocar mini-conciertos virtuales, personales y gratuitos para cualquier persona que necesite un respiro musical. Estos conciertos se realizan a través de videollamadas, adaptándose a la coyuntura en la que vivimos y ofreciendo una experiencia íntima entre oyente e intérprete que por lo general no se logra en las salas de conciertos.',
        pt: 'Música para Respirar 24/7 é uma instalação artística na qual músicos e músicos de todo o mundo estão disponíveis 24 horas por dia durante uma semana, prontos para tocar mini-concertos virtuais, pessoais e gratuitos para quem precisa de uma pausa musical. Estes concertos são realizados através de videochamadas, adaptando-se à situação em que vivemos e proporcionando uma experiência íntima entre ouvinte e intérprete que geralmente não se consegue nas salas de concerto. '
    },
    'aboutDescriptionP2': {
        en: 'Música para Respirar 24/7 was created to pay tribute and offer a brief respite to overstretched healthcare workers and anybody impacted by the COVID-19 pandemic. Besides helping to reduce feelings of isolation and providing a space for tranquility for the listener, Música para Respirar 24/7 also aims to democratize classical music by using social media to reach communities with limited access to the arts..',
        es: 'La iniciativa fue creada por La Sociedad Boliviana de Música de Cámara (La Sociedad) en agosto de 2020, como una respuesta artística a la crisis sanitaria global causada por la pandemia del COVID-19. Bolivia se encontraba en una situación crítica, con hospitales colapsados y en medio de una crisis política y social que se sumaba la incertidumbre de la pandemia. Los miembros de La Sociedad queríamos ofrecer algo innovador, que sea más personal que el contenido al que se tenía acceso en redes sociales. Nuestra meta era acercarnos a la experiencia de los conciertos en vivo, que contienen un nivel de energía distinta a los conciertos grabados.',
        pt: 'A iniciativa foi criada por La Sociedad Boliviana de Música de Cámara (La Sociedad) em agosto de 2020, como uma resposta artística à crise de saúde global causada pela pandemia COVID-19. A Bolívia estava em uma situação crítica, com hospitais destruídos e em meio a uma crise política e social que aumentou a incerteza da pandemia. Os membros da The Society queriam oferecer algo inovador, que fosse mais pessoal do que o conteúdo que foi acessado nas redes sociais. Nosso objetivo era chegar mais perto da experiência de shows ao vivo, que contêm um nível de energia diferente dos shows gravados.'
        },
    'aboutDescriptionP3': {
        en: 'Since it was launched in August of 2020, Musica para Respirar 24/7 has brought together more than 80 musicians from across Latin America, Europe and the US and performed to more than 12,000 people in 50 countries around the world.  Healthcare workers, vulnerable children in orphanages and elderly people in retirement homes have been among the recipients of concerts. Música para Respirar 24/7 has also provided respite to hundreds of survivors of Covid-19 and their friends and families around the world.',
        pt: 'A semana piloto de Música para Respirar 24/7 foi concebida como uma homenagem ao pessoal de saúde e aos turnos extenuantes que realizam para cuidar da população. Os músicos que participam neste projeto vivenciam um exercício de empatia, no qual doam o seu tempo para estarem disponíveis, em turnos de até 12 horas consecutivas, de forma a gerar espaços sonoros de tranquilidade e distração a quem precisa. Até o momento, nossos shows alcançaram mais de 6.000 pessoas em 46 países. '
    },
    'aboutLaSociedad': {
        en: 'The Bolivian Chamber Music Society was born… .. here I need you to write a small review Cami, because you can better explain how it was born. 1 or 2 paragraphs would be fine. Perhaps in the lower part of this section you could enter the photos in small of the members of the society ',
        es: 'La Sociedad Boliviana de Música de Cámara nació ….. acá necesito que escribas una pequeña reseña Cami, porque tu puedes explicar mejor cómo nació. 1 o 2 párrafos estaría bien. Tal vez en la parte de debajo de esta sección podrían entrar las fotos en peque de los miembros de la sociedad',
        pt: 'Nasceu a Sociedade Boliviana de Música de Câmara… .. aqui preciso que você escreva uma pequena resenha, Cami, porque você pode explicar melhor como ela nasceu. 1 ou 2 parágrafos seriam suficientes. Talvez no final desta seção você possa inserir as pequenas fotos dos membros da sociedade '
        },
}
