export default {
    'aboutDescriptionP1': {
        en: 'Música Para Respirar 24/7 is an artistic installation in which musicians and musicians from around the world are available 24 hours a day for a week, ready to play virtual, personal and free mini-concerts for anyone who needs a musical break. These concerts are carried out through video calls, adapting to the situation in which we live and offering an intimate experience between listener and performer that is generally not achieved in concert halls.',
        es: 'Música para Respirar 24/7 es una instalación artística en la cual músicos y músicas de alrededor del mundo están disponibles las 24 horas del día durante una semana, listos para tocar mini-conciertos virtuales, personales y gratuitos para cualquier persona que necesite un respiro musical. Estos conciertos se realizan a través de videollamadas, adaptándose a la coyuntura en la que vivimos y ofreciendo una experiencia íntima entre oyente e intérprete que por lo general no se logra en las salas de conciertos.',
        pt: 'Música para Respirar 24/7 é uma instalação artística na qual músicos e músicos de todo o mundo estão disponíveis 24 horas por dia durante uma semana, prontos para tocar mini-concertos virtuais, pessoais e gratuitos para quem precisa de uma pausa musical. Estes concertos são realizados através de videochamadas, adaptando-se à situação em que vivemos e proporcionando uma experiência íntima entre ouvinte e intérprete que geralmente não se consegue nas salas de concerto. '
    },
    'aboutDescriptionP2': {
        en: 'The initiative was created by La Sociedad Boliviana de Música de Cámara (La Sociedad) in August 2020, as an artistic response to the global health crisis caused by the COVID-19 pandemic. Bolivia was in a critical situation, with collapsed hospitals and in the midst of a political and social crisis that added to the uncertainty of the pandemic. The members of La Sociedad wanted to offer something innovative, that is more personal than the content that was accessed on social networks. Our goal was to get closer to the experience of live concerts, which contain a different level of energy than recorded concerts.',
        es: 'La iniciativa fue creada por La Sociedad Boliviana de Música de Cámara (La Sociedad) en agosto de 2020, como una respuesta artística a la crisis sanitaria global causada por la pandemia del COVID-19. Bolivia se encontraba en una situación crítica, con hospitales colapsados y en medio de una crisis política y social que se sumaba la incertidumbre de la pandemia. Los miembros de La Sociedad queríamos ofrecer algo innovador, que sea más personal que el contenido al que se tenía acceso en redes sociales. Nuestra meta era acercarnos a la experiencia de los conciertos en vivo, que contienen un nivel de energía distinta a los conciertos grabados.',
        pt: 'A iniciativa foi criada por La Sociedad Boliviana de Música de Cámara (La Sociedad) em agosto de 2020, como uma resposta artística à crise de saúde global causada pela pandemia COVID-19. A Bolívia estava em uma situação crítica, com hospitais destruídos e em meio a uma crise política e social que aumentou a incerteza da pandemia. Os membros da The Society queriam oferecer algo inovador, que fosse mais pessoal do que o conteúdo que foi acessado nas redes sociais. Nosso objetivo era chegar mais perto da experiência de shows ao vivo, que contêm um nível de energia diferente dos shows gravados.'
        },
    'aboutDescriptionP3': {
        en: 'The Música para Respirar 24/7 pilot week was intended as a tribute to health personnel and the strenuous shifts they take to care for the population. The musicians who participate in this project experience an exercise of empathy, in which they give their time to be available, in shifts of up to 12 hours in a row, in order to generate sound spaces of tranquility and distraction to those who need it. To date, our concerts have reached more than 6000 people in 46 countries. ',
        es: 'La semana piloto de Música para Respirar 24/7 fue pensada como un homenaje al personal de salud y los turnos extenuantes que realizan para cuidar a la población. Los músicos que participan en este proyecto experimentan un ejercicio de empatía, en el que bridan su tiempo para estar disponibles, en turnos de hasta 12 horas seguidas, con el fin de generar espacios sonoros de tranquilidad y distracción a quienes lo necesiten. Hasta la fecha, nuestros conciertos han llegado a más de 6000 personas en 46 países.',
        pt: 'A semana piloto de Música para Respirar 24/7 foi concebida como uma homenagem ao pessoal de saúde e aos turnos extenuantes que realizam para cuidar da população. Os músicos que participam neste projeto vivenciam um exercício de empatia, no qual doam o seu tempo para estarem disponíveis, em turnos de até 12 horas consecutivas, de forma a gerar espaços sonoros de tranquilidade e distração a quem precisa. Até o momento, nossos shows alcançaram mais de 6.000 pessoas em 46 países. '
    },
    'aboutLaSociedad': {
        en: 'The Bolivian Chamber Music Society was born… .. here I need you to write a small review Cami, because you can better explain how it was born. 1 or 2 paragraphs would be fine. Perhaps in the lower part of this section you could enter the photos in small of the members of the society ',
        es: 'La Sociedad Boliviana de Música de Cámara nació ….. acá necesito que escribas una pequeña reseña Cami, porque tu puedes explicar mejor cómo nació. 1 o 2 párrafos estaría bien. Tal vez en la parte de debajo de esta sección podrían entrar las fotos en peque de los miembros de la sociedad',
        pt: 'Nasceu a Sociedade Boliviana de Música de Câmara… .. aqui preciso que você escreva uma pequena resenha, Cami, porque você pode explicar melhor como ela nasceu. 1 ou 2 parágrafos seriam suficientes. Talvez no final desta seção você possa inserir as pequenas fotos dos membros da sociedade '
        },
}
